"use client";

import { useState, useEffect, useRef } from "react";
import { api, saveSession } from "../lib/api";

const FEATURES = [
  { icon: "🧠", title: "AI Resume Parser", desc: "Extracts skills, experience & 40+ data points from any resume in seconds." },
  { icon: "⚡", title: "Smart Auto-Fill", desc: "Chrome extension fills job forms instantly using your parsed profile — 1-click apply." },
  { icon: "📊", title: "Career Analytics", desc: "Track applications, interview conversion rates and skill gap heatmaps." },
  { icon: "🗺️", title: "AI Roadmap", desc: "Week-by-week learning plan generated for your exact target role." },
  { icon: "🎤", title: "Interview Prep", desc: "Role-specific question banks with ideal answers, generated by AI." },
  { icon: "🔍", title: "Multi-Portal Discovery", desc: "Aggregates fresh jobs from Naukri, LinkedIn, Foundit, Indeed & more daily." },
];

const STEPS = [
  { n: "01", title: "Upload Resume", desc: "Drop your PDF once. AI extracts everything — skills, experience, projects, education." },
  { n: "02", title: "Discover Jobs", desc: "AI scours 20+ portals and scores every role against your profile in real time." },
  { n: "03", title: "Auto-Apply", desc: "Chrome extension fills application forms in 4 seconds using your parsed data." },
  { n: "04", title: "Track & Improve", desc: "Analytics show your funnel — from views to offers — and exactly which skills to upskill." },
];

const PLANS = [
  { name: "Free", price: "₹0", period: "forever", color: "#6b7280", highlight: false, cta: "Get Started", features: ["25 AI credits/month", "Resume parsing & profile", "25 applications/day", "Chrome extension (manual)", "Basic analytics"] },
  { name: "Pro", price: "₹1,900", period: "/mo", color: "#4f8aff", highlight: true, cta: "Upgrade to Pro", features: ["1,000 AI credits/month", "Unlimited tracking", "AI Auto-Fill extension", "Interview prep packs", "Career roadmap AI", "Skill gap analysis", "500 jobs/day"] },
  { name: "Elite", price: "₹4,900", period: "/mo", color: "#7c5cfc", highlight: false, cta: "Go Elite", features: ["5,000 AI credits/month", "Everything in Pro", "Priority AI processing", "2,000 jobs/day", "Advanced analytics", "Priority support"] },
];

const TESTIMONIALS = [
  { name: "Rohit M.", role: "SWE @ Zepto", text: "Got 3 interviews in my first week. The auto-fill alone saved me 6 hours of copy-pasting.", stars: 5 },
  { name: "Priya S.", role: "Product @ Razorpay", text: "The roadmap feature told me exactly what to learn. Cleared my product role in 8 weeks.", stars: 5 },
  { name: "Arjun K.", role: "Data Science @ Meesho", text: "Match scores are surprisingly accurate. Stopped wasting time on poor-fit jobs entirely.", stars: 5 },
];

function useInView(threshold = 0.15) {
  const ref = useRef<HTMLDivElement>(null);
  const [visible, setVisible] = useState(false);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const obs = new IntersectionObserver(([e]) => { if (e.isIntersecting) { setVisible(true); obs.disconnect(); } }, { threshold });
    obs.observe(el);
    return () => obs.disconnect();
  }, [threshold]);
  return { ref, visible };
}

export default function LandingPage() {
  const [navScrolled, setNavScrolled] = useState(false);
  useEffect(() => {
    const fn = () => setNavScrolled(window.scrollY > 40);
    window.addEventListener("scroll", fn);
    return () => window.removeEventListener("scroll", fn);
  }, []);

  const featRef = useInView();
  const stepsRef = useInView();
  const plansRef = useInView();
  const testiRef = useInView();

  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Syne:wght@400;500;600;700;800&family=DM+Sans:ital,opsz,wght@0,9..40,300;0,9..40,400;0,9..40,500;0,9..40,600;1,9..40,300&display=swap');

        /* ── LANDING-SPECIFIC TOKENS ── */
        :root {
          --lnd-bg:     #04060e;
          --lnd-s1:     rgba(255,255,255,0.032);
          --lnd-s2:     rgba(255,255,255,0.052);
          --lnd-bd:     rgba(255,255,255,0.07);
          --lnd-bd2:    rgba(255,255,255,0.13);
          --lnd-tx:     #eef2ff;
          --lnd-tx2:    #8b95b0;
          --lnd-tx3:    #4a5368;
          --lnd-ac:     #4f8aff;
          --lnd-ac2:    #7c5cfc;
          --lnd-gn:     #22d3a0;
          --lnd-r:      14px;
        }

        /* hero orb animation */
        @keyframes float-orb { 0%,100%{transform:translate(0,0) scale(1)} 33%{transform:translate(30px,-20px) scale(1.05)} 66%{transform:translate(-20px,15px) scale(0.97)} }
        @keyframes fade-up   { from{opacity:0;transform:translateY(28px)} to{opacity:1;transform:translateY(0)} }
        @keyframes ticker    { 0%{transform:translateX(0)} 100%{transform:translateX(-50%)} }
        @keyframes counter-glow { 0%,100%{box-shadow:0 0 20px rgba(79,138,255,0.18)} 50%{box-shadow:0 0 40px rgba(79,138,255,0.38)} }
        @keyframes pulse-dot { 0%,100%{opacity:1} 50%{opacity:0.25} }
        @keyframes slide-reveal { from{opacity:0;transform:translateY(22px)} to{opacity:1;transform:translateY(0)} }

        .lnd-body { background: var(--lnd-bg); color: var(--lnd-tx); font-family: 'DM Sans', sans-serif; }

        /* NAV */
        .lnd-nav {
          position: fixed; top: 0; left: 0; right: 0; z-index: 200;
          display: flex; align-items: center; justify-content: space-between;
          padding: 0 6vw; height: 62px;
          transition: background 0.3s, border-color 0.3s;
          border-bottom: 1px solid transparent;
        }
        .lnd-nav.scrolled { background: rgba(4,6,14,0.88); border-color: var(--lnd-bd); backdrop-filter: blur(18px); }
        .lnd-logo { display:flex; align-items:center; gap:10px; font-family:'Syne',sans-serif; font-size:16px; font-weight:800; letter-spacing:-0.01em; }
        .lnd-logo-dot { width:8px; height:8px; border-radius:50%; background:var(--lnd-ac); animation:pulse-dot 2.2s infinite; flex-shrink:0; }
        .lnd-logo-icon { width:34px;height:34px; border-radius:10px; background:linear-gradient(135deg,var(--lnd-ac),var(--lnd-ac2)); display:grid; place-items:center; font-size:17px; box-shadow:0 0 22px rgba(79,138,255,0.35); }
        .lnd-nav-links { display:flex; align-items:center; gap:28px; }
        .lnd-nav-links a { font-size:13.5px; color:var(--lnd-tx2); transition:color 0.15s; font-weight:500; }
        .lnd-nav-links a:hover { color:var(--lnd-tx); }
        .lnd-nav-btns { display:flex; align-items:center; gap:10px; }
        .lnd-btn-ghost { padding:7px 16px; border-radius:8px; border:1px solid var(--lnd-bd2); background:transparent; color:var(--lnd-tx); font-size:13px; font-weight:600; cursor:pointer; transition:all 0.15s; font-family:'DM Sans',sans-serif; }
        .lnd-btn-ghost:hover { background:rgba(255,255,255,0.06); }
        .lnd-btn-primary { padding:8px 18px; border-radius:8px; border:none; background:var(--lnd-ac); color:#fff; font-size:13px; font-weight:700; cursor:pointer; transition:all 0.15s; box-shadow:0 0 20px rgba(79,138,255,0.3); font-family:'DM Sans',sans-serif; }
        .lnd-btn-primary:hover { background:#6b9fff; box-shadow:0 0 28px rgba(79,138,255,0.45); transform:translateY(-1px); }

        /* HERO */
        .lnd-hero {
          min-height: 100vh;
          display: flex; flex-direction: column; justify-content: center;
          padding: 120px 6vw 80px;
          position: relative; overflow: hidden;
        }
        .lnd-hero-orb1 { position:absolute; top:-10%; left:-8%; width:700px; height:700px; border-radius:50%; background:radial-gradient(circle,rgba(79,138,255,0.10) 0%,transparent 65%); animation:float-orb 14s ease-in-out infinite; pointer-events:none; }
        .lnd-hero-orb2 { position:absolute; bottom:-15%; right:-5%; width:600px; height:600px; border-radius:50%; background:radial-gradient(circle,rgba(124,92,252,0.09) 0%,transparent 65%); animation:float-orb 18s ease-in-out infinite reverse; pointer-events:none; }
        .lnd-eyebrow { display:inline-flex; align-items:center; gap:8px; padding:5px 14px; background:rgba(79,138,255,0.08); border:1px solid rgba(79,138,255,0.2); border-radius:99px; font-size:12px; font-weight:700; color:var(--lnd-ac); letter-spacing:0.06em; text-transform:uppercase; width:fit-content; margin-bottom:22px; animation: fade-up 0.7s ease both; }
        .lnd-h1 { font-family:'Syne',sans-serif; font-size:clamp(44px,6vw,82px); font-weight:800; line-height:1.02; letter-spacing:-0.035em; margin-bottom:22px; animation:fade-up 0.7s 0.1s ease both; }
        .lnd-h1 em { font-style:normal; background:linear-gradient(135deg,var(--lnd-ac) 0%,var(--lnd-ac2) 100%); -webkit-background-clip:text; -webkit-text-fill-color:transparent; background-clip:text; }
        .lnd-hero-sub { font-size:17px; color:var(--lnd-tx2); line-height:1.75; max-width:560px; margin-bottom:36px; animation:fade-up 0.7s 0.18s ease both; }
        .lnd-hero-cta { display:flex; gap:12px; flex-wrap:wrap; margin-bottom:60px; animation:fade-up 0.7s 0.26s ease both; }
        .lnd-cta-big { padding:14px 28px; border-radius:10px; background:var(--lnd-ac); border:none; color:#fff; font-size:15px; font-weight:700; cursor:pointer; box-shadow:0 0 30px rgba(79,138,255,0.35); transition:all 0.15s; font-family:'DM Sans',sans-serif; }
        .lnd-cta-big:hover { transform:translateY(-2px); box-shadow:0 0 40px rgba(79,138,255,0.5); }
        .lnd-cta-outline { padding:14px 28px; border-radius:10px; background:transparent; border:1px solid var(--lnd-bd2); color:var(--lnd-tx); font-size:15px; font-weight:600; cursor:pointer; transition:all 0.15s; font-family:'DM Sans',sans-serif; }
        .lnd-cta-outline:hover { background:rgba(255,255,255,0.05); }
        .lnd-stats { display:flex; gap:36px; flex-wrap:wrap; animation:fade-up 0.7s 0.34s ease both; }
        .lnd-stat { line-height:1.2; }
        .lnd-stat-v { font-family:'Syne',sans-serif; font-size:32px; font-weight:800; color:var(--lnd-tx); letter-spacing:-0.02em; }
        .lnd-stat-l { font-size:12px; color:var(--lnd-tx3); margin-top:3px; }
        .lnd-stat-div { width:1px; background:var(--lnd-bd2); align-self:stretch; }

        /* DASHBOARD PREVIEW */
        .lnd-preview {
          margin-top: 72px;
          position: relative;
          animation: fade-up 0.9s 0.42s ease both;
        }
        .lnd-preview-glow { position:absolute; inset:-30px; background:radial-gradient(ellipse 70% 50% at 50% 50%, rgba(79,138,255,0.1) 0%, transparent 65%); pointer-events:none; }
        .lnd-preview-card {
          background:rgba(8,13,24,0.9); border:1px solid var(--lnd-bd2); border-radius:18px;
          overflow:hidden; box-shadow:0 24px 80px rgba(0,0,0,0.6);
          max-width:900px; margin:0 auto;
        }
        .lnd-preview-bar { height:38px; background:rgba(255,255,255,0.03); border-bottom:1px solid var(--lnd-bd); display:flex; align-items:center; padding:0 14px; gap:6px; }
        .lnd-preview-dot { width:11px; height:11px; border-radius:50%; }
        .lnd-preview-body { padding:20px 24px; display:grid; grid-template-columns:1fr 1fr 1fr; gap:14px; }
        .lnd-preview-stat { background:rgba(255,255,255,0.025); border:1px solid var(--lnd-bd); border-radius:10px; padding:14px 16px; }
        .lnd-preview-stat-v { font-family:'Syne',sans-serif; font-size:28px; font-weight:800; }
        .lnd-preview-stat-l { font-size:11px; color:var(--lnd-tx2); margin-top:3px; }
        .lnd-preview-jobs { grid-column:1/-1; display:flex; flex-direction:column; gap:8px; }
        .lnd-preview-job { background:rgba(255,255,255,0.02); border:1px solid var(--lnd-bd); border-radius:8px; padding:11px 14px; display:flex; justify-content:space-between; align-items:center; }
        .lnd-preview-job-title { font-size:13px; font-weight:600; }
        .lnd-preview-job-co { font-size:11px; color:var(--lnd-tx2); margin-top:2px; }
        .lnd-match-chip { padding:3px 10px; border-radius:99px; font-size:11px; font-weight:700; }
        .match-hi { background:rgba(34,211,160,0.12); color:#22d3a0; border:1px solid rgba(34,211,160,0.22); }
        .match-md { background:rgba(79,138,255,0.12); color:#4f8aff; border:1px solid rgba(79,138,255,0.22); }

        /* TICKER */
        .lnd-ticker-wrap { overflow:hidden; border-top:1px solid var(--lnd-bd); border-bottom:1px solid var(--lnd-bd); padding:14px 0; background:rgba(255,255,255,0.015); margin:80px 0; }
        .lnd-ticker { display:flex; gap:48px; width:max-content; animation:ticker 28s linear infinite; white-space:nowrap; }
        .lnd-ticker-item { display:flex; align-items:center; gap:10px; font-size:13px; font-weight:600; color:var(--lnd-tx2); }
        .lnd-ticker-item span { color:var(--lnd-ac); }

        /* SECTION COMMON */
        .lnd-section { padding:80px 6vw; position:relative; z-index:1; }
        .lnd-section-eyebrow { font-size:11px; font-weight:700; color:var(--lnd-ac); letter-spacing:0.12em; text-transform:uppercase; margin-bottom:10px; }
        .lnd-section-h2 { font-family:'Syne',sans-serif; font-size:clamp(30px,4vw,48px); font-weight:800; letter-spacing:-0.025em; line-height:1.1; margin-bottom:14px; }
        .lnd-section-sub { font-size:15px; color:var(--lnd-tx2); line-height:1.7; max-width:560px; margin-bottom:52px; }

        /* FEATURES GRID */
        .lnd-feat-grid { display:grid; grid-template-columns:repeat(3,1fr); gap:18px; }
        .lnd-feat-card {
          background:var(--lnd-s1); border:1px solid var(--lnd-bd); border-radius:var(--lnd-r); padding:24px;
          transition:all 0.18s;
        }
        .lnd-feat-card:hover { background:var(--lnd-s2); border-color:var(--lnd-bd2); transform:translateY(-3px); box-shadow:0 8px 32px rgba(0,0,0,0.4); }
        .lnd-feat-icon { width:44px;height:44px; border-radius:11px; background:rgba(79,138,255,0.1); border:1px solid rgba(79,138,255,0.18); display:grid; place-items:center; font-size:20px; margin-bottom:16px; }
        .lnd-feat-title { font-family:'Syne',sans-serif; font-size:15px; font-weight:700; margin-bottom:7px; }
        .lnd-feat-desc { font-size:13px; color:var(--lnd-tx2); line-height:1.7; }

        /* STEPS */
        .lnd-steps-grid { display:grid; grid-template-columns:repeat(4,1fr); gap:0; position:relative; }
        .lnd-steps-grid::before { content:''; position:absolute; top:28px; left:10%; right:10%; height:1px; background:linear-gradient(90deg,transparent,var(--lnd-bd2),var(--lnd-ac),var(--lnd-bd2),transparent); }
        .lnd-step { padding:0 20px 0 0; position:relative; z-index:1; }
        .lnd-step-num { width:56px; height:56px; border-radius:50%; background:linear-gradient(135deg,var(--lnd-ac),var(--lnd-ac2)); display:grid; place-items:center; font-family:'Syne',sans-serif; font-size:16px; font-weight:800; color:#fff; margin-bottom:18px; box-shadow:0 0 28px rgba(79,138,255,0.3); }
        .lnd-step-title { font-family:'Syne',sans-serif; font-size:15px; font-weight:700; margin-bottom:7px; }
        .lnd-step-desc { font-size:13px; color:var(--lnd-tx2); line-height:1.7; }

        /* PLANS */
        .lnd-plans-grid { display:grid; grid-template-columns:repeat(3,1fr); gap:18px; align-items:start; }
        .lnd-plan { background:var(--lnd-s1); border:1px solid var(--lnd-bd); border-radius:var(--lnd-r); padding:28px; position:relative; overflow:hidden; transition:all 0.18s; }
        .lnd-plan:hover { transform:translateY(-3px); box-shadow:0 12px 40px rgba(0,0,0,0.4); }
        .lnd-plan.pop { background:rgba(79,138,255,0.05); border-color:rgba(79,138,255,0.28); }
        .lnd-plan-badge { position:absolute; top:14px; right:-22px; background:var(--lnd-ac); color:#fff; font-size:9px; font-weight:800; letter-spacing:0.1em; padding:3px 30px; transform:rotate(35deg); }
        .lnd-plan-name { font-size:12px; font-weight:700; padding:3px 10px; border-radius:99px; display:inline-block; margin-bottom:14px; }
        .lnd-plan-price { font-family:'Syne',sans-serif; font-size:42px; font-weight:800; letter-spacing:-0.025em; line-height:1; margin-bottom:4px; }
        .lnd-plan-period { font-size:13px; color:var(--lnd-tx2); margin-bottom:20px; }
        .lnd-plan-features { list-style:none; display:flex; flex-direction:column; gap:9px; margin-bottom:24px; }
        .lnd-plan-features li { font-size:13px; color:var(--lnd-tx2); display:flex; gap:9px; }
        .lnd-plan-features li::before { content:'✓'; color:var(--lnd-gn); font-weight:700; flex-shrink:0; }
        .lnd-plan-cta { display:block; text-align:center; padding:11px; border-radius:9px; font-size:13px; font-weight:700; cursor:pointer; transition:all 0.15s; text-decoration:none; }

        /* TESTIMONIALS */
        .lnd-testi-grid { display:grid; grid-template-columns:repeat(3,1fr); gap:18px; }
        .lnd-testi { background:var(--lnd-s1); border:1px solid var(--lnd-bd); border-radius:var(--lnd-r); padding:24px; }
        .lnd-testi-stars { font-size:13px; margin-bottom:12px; letter-spacing:2px; }
        .lnd-testi-text { font-size:14px; color:var(--lnd-tx); line-height:1.75; margin-bottom:18px; font-style:italic; }
        .lnd-testi-meta { display:flex; flex-direction:column; gap:2px; }
        .lnd-testi-name { font-size:13px; font-weight:700; }
        .lnd-testi-role { font-size:12px; color:var(--lnd-tx3); }

        /* REVEAL ANIMATION */
        .reveal { opacity:0; transform:translateY(24px); transition:opacity 0.6s ease, transform 0.6s ease; }
        .reveal.in { opacity:1; transform:translateY(0); }
        .reveal-delay-1 { transition-delay: 0.1s; }
        .reveal-delay-2 { transition-delay: 0.2s; }
        .reveal-delay-3 { transition-delay: 0.3s; }
        .reveal-delay-4 { transition-delay: 0.4s; }
        .reveal-delay-5 { transition-delay: 0.5s; }
        .reveal-delay-6 { transition-delay: 0.6s; }

        /* CTA BANNER */
        .lnd-cta-banner { background:linear-gradient(135deg,rgba(79,138,255,0.12),rgba(124,92,252,0.12)); border:1px solid rgba(79,138,255,0.22); border-radius:20px; padding:56px 5%; text-align:center; }

        /* FOOTER */
        .lnd-footer { border-top:1px solid var(--lnd-bd); padding:32px 6vw; display:flex; justify-content:space-between; align-items:center; flex-wrap:wrap; gap:16px; }
        .lnd-footer-links { display:flex; gap:20px; }
        .lnd-footer-links a { font-size:12px; color:var(--lnd-tx3); transition:color 0.15s; }
        .lnd-footer-links a:hover { color:var(--lnd-tx2); }

        @media(max-width:900px) {
          .lnd-feat-grid, .lnd-plans-grid, .lnd-testi-grid { grid-template-columns:1fr 1fr; }
          .lnd-steps-grid { grid-template-columns:1fr 1fr; gap:28px; }
          .lnd-steps-grid::before { display:none; }
          .lnd-nav-links { display:none; }
        }
        @media(max-width:600px) {
          .lnd-feat-grid, .lnd-plans-grid, .lnd-testi-grid, .lnd-steps-grid { grid-template-columns:1fr; }
          .lnd-preview-body { grid-template-columns:1fr; }
        }
      `}</style>

      <div className="lnd-body">

        {/* ── NAV ── */}
        <nav className={`lnd-nav ${navScrolled ? "scrolled" : ""}`}>
          <div className="lnd-logo">
            <div className="lnd-logo-icon">🤖</div>
            AI Job Copilot
            <div className="lnd-logo-dot" />
          </div>
          <div className="lnd-nav-links">
            <a href="#features">Features</a>
            <a href="#how-it-works">How it works</a>
            <a href="#pricing">Pricing</a>
          </div>
          <div className="lnd-nav-btns">
            <button className="lnd-btn-ghost" onClick={() => window.location.href = "/login"}>Sign in</button>
            <button className="lnd-btn-primary" onClick={() => window.location.href = "/signup"}>Start free →</button>
          </div>
        </nav>

        {/* ── HERO ── */}
        <section className="lnd-hero">
          <div className="lnd-hero-orb1" />
          <div className="lnd-hero-orb2" />

          <div className="lnd-eyebrow">🤖 AI-Powered Career Platform</div>
          <h1 className="lnd-h1">
            Apply smarter.<br />
            <em>Land faster.</em>
          </h1>
          <p className="lnd-hero-sub">
            Upload your resume once. AI parses your profile, discovers matched jobs across 20+ portals, auto-fills applications in 4 seconds, and tracks every outcome — all from one command center.
          </p>

          <div className="lnd-hero-cta">
            <button className="lnd-cta-big" onClick={() => window.location.href = "/signup">Start free — 25 AI credits →</button>
            <button className="lnd-cta-outline" onClick={() => window.location.href = "/login"}>Sign in</button>
          </div>

          <div className="lnd-stats">
            <div className="lnd-stat"><div className="lnd-stat-v">10x</div><div className="lnd-stat-l">Faster applications</div></div>
            <div className="lnd-stat-div" />
            <div className="lnd-stat"><div className="lnd-stat-v">85%</div><div className="lnd-stat-l">Auto-fill accuracy</div></div>
            <div className="lnd-stat-div" />
            <div className="lnd-stat"><div className="lnd-stat-v">20+</div><div className="lnd-stat-l">Job portals covered</div></div>
            <div className="lnd-stat-div" />
            <div className="lnd-stat"><div className="lnd-stat-v">Free</div><div className="lnd-stat-l">To start, always</div></div>
          </div>

          {/* Dashboard Preview */}
          <div className="lnd-preview">
            <div className="lnd-preview-glow" />
            <div className="lnd-preview-card">
              <div className="lnd-preview-bar">
                <div className="lnd-preview-dot" style={{ background: "#ff5f57" }} />
                <div className="lnd-preview-dot" style={{ background: "#febc2e" }} />
                <div className="lnd-preview-dot" style={{ background: "#28c840" }} />
                <div style={{ marginLeft: 10, fontSize: 11, color: "var(--lnd-tx3)", fontFamily: "monospace" }}>AI Job Copilot — Dashboard</div>
              </div>
              <div className="lnd-preview-body">
                <div className="lnd-preview-stat"><div className="lnd-preview-stat-v" style={{ color: "var(--lnd-ac)" }}>247</div><div className="lnd-preview-stat-l">Jobs Captured Today</div></div>
                <div className="lnd-preview-stat"><div className="lnd-preview-stat-v" style={{ color: "var(--lnd-gn)" }}>38</div><div className="lnd-preview-stat-l">High Matches (≥70%)</div></div>
                <div className="lnd-preview-stat"><div className="lnd-preview-stat-v">12</div><div className="lnd-preview-stat-l">Applications Tracked</div></div>
                <div className="lnd-preview-jobs">
                  {[
                    { title: "Senior Frontend Engineer", co: "Razorpay · Bangalore", match: 94, hi: true },
                    { title: "Full Stack Developer", co: "Zepto · Mumbai", match: 88, hi: true },
                    { title: "React Developer", co: "Meesho · Remote", match: 76, hi: false },
                  ].map((j) => (
                    <div key={j.title} className="lnd-preview-job">
                      <div>
                        <div className="lnd-preview-job-title">{j.title}</div>
                        <div className="lnd-preview-job-co">{j.co}</div>
                      </div>
                      <div className={`lnd-match-chip ${j.hi ? "match-hi" : "match-md"}`}>{j.match}% match</div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* ── TICKER ── */}
        <div className="lnd-ticker-wrap">
          <div className="lnd-ticker">
            {["Resume Parsing", "Smart Auto-Fill", "Career Analytics", "AI Roadmap", "Interview Prep", "20+ Job Portals", "Match Scoring", "Skill Gap Analysis", "Resume Parsing", "Smart Auto-Fill", "Career Analytics", "AI Roadmap", "Interview Prep", "20+ Job Portals", "Match Scoring", "Skill Gap Analysis"].map((t, i) => (
              <div key={i} className="lnd-ticker-item"><span>✦</span> {t}</div>
            ))}
          </div>
        </div>

        {/* ── FEATURES ── */}
        <section id="features" className="lnd-section">
          <div className="lnd-section-eyebrow">Everything you need</div>
          <h2 className="lnd-section-h2">Your complete<br />career operating system</h2>
          <p className="lnd-section-sub">Every feature built for one goal — getting you hired faster, with less manual work.</p>
          <div ref={featRef.ref} className="lnd-feat-grid">
            {FEATURES.map((f, i) => (
              <div key={f.title} className={`lnd-feat-card reveal ${featRef.visible ? "in" : ""} reveal-delay-${i + 1}`}>
                <div className="lnd-feat-icon">{f.icon}</div>
                <div className="lnd-feat-title">{f.title}</div>
                <div className="lnd-feat-desc">{f.desc}</div>
              </div>
            ))}
          </div>
        </section>

        {/* ── HOW IT WORKS ── */}
        <section id="how-it-works" className="lnd-section" style={{ background: "rgba(255,255,255,0.012)", borderTop: "1px solid var(--lnd-bd)", borderBottom: "1px solid var(--lnd-bd)" }}>
          <div className="lnd-section-eyebrow">Process</div>
          <h2 className="lnd-section-h2">From resume to offer<br />in 4 steps</h2>
          <p className="lnd-section-sub">Set up in 5 minutes. Then let the AI do the heavy lifting.</p>
          <div ref={stepsRef.ref} className="lnd-steps-grid">
            {STEPS.map((s, i) => (
              <div key={s.n} className={`lnd-step reveal ${stepsRef.visible ? "in" : ""} reveal-delay-${i + 1}`}>
                <div className="lnd-step-num">{s.n}</div>
                <div className="lnd-step-title">{s.title}</div>
                <div className="lnd-step-desc">{s.desc}</div>
              </div>
            ))}
          </div>
        </section>

        {/* ── TESTIMONIALS ── */}
        <section className="lnd-section">
          <div className="lnd-section-eyebrow">Social Proof</div>
          <h2 className="lnd-section-h2">Loved by job seekers</h2>
          <p className="lnd-section-sub">Real results from people who took their job search seriously.</p>
          <div ref={testiRef.ref} className="lnd-testi-grid">
            {TESTIMONIALS.map((t, i) => (
              <div key={t.name} className={`lnd-testi reveal ${testiRef.visible ? "in" : ""} reveal-delay-${i + 1}`}>
                <div className="lnd-testi-stars">{"★".repeat(t.stars)}</div>
                <div className="lnd-testi-text">&ldquo;{t.text}&rdquo;</div>
                <div className="lnd-testi-meta">
                  <div className="lnd-testi-name">{t.name}</div>
                  <div className="lnd-testi-role">{t.role}</div>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* ── PRICING ── */}
        <section id="pricing" className="lnd-section" style={{ background: "rgba(255,255,255,0.012)", borderTop: "1px solid var(--lnd-bd)", borderBottom: "1px solid var(--lnd-bd)" }}>
          <div className="lnd-section-eyebrow">Pricing</div>
          <h2 className="lnd-section-h2">Simple, honest pricing</h2>
          <p className="lnd-section-sub">Buy AI credits, use them on features you need. No seat fees. Cancel anytime.</p>
          <div ref={plansRef.ref} className="lnd-plans-grid">
            {PLANS.map((p, i) => (
              <div key={p.name} className={`lnd-plan ${p.highlight ? "pop" : ""} reveal ${plansRef.visible ? "in" : ""} reveal-delay-${i + 1}`}>
                {p.highlight && <div className="lnd-plan-badge">POPULAR</div>}
                <div className="lnd-plan-name" style={{ background: `${p.color}18`, color: p.color, border: `1px solid ${p.color}33` }}>{p.name}</div>
                <div className="lnd-plan-price">{p.price}</div>
                <div className="lnd-plan-period">{p.period}</div>
                <ul className="lnd-plan-features">
                  {p.features.map((f) => <li key={f}>{f}</li>)}
                </ul>
                <a
                  href={p.highlight ? "/signup" : (p.name === "Free" ? "/signup" : "/login?redirect=/billing")}
                  className="lnd-plan-cta"
                  style={{
                    background: p.highlight ? "var(--lnd-ac)" : "rgba(255,255,255,0.05)",
                    color: p.highlight ? "#fff" : "var(--lnd-tx)",
                    border: p.highlight ? "none" : "1px solid var(--lnd-bd2)",
                  }}
                >
                  {p.cta}
                </a>
              </div>
            ))}
          </div>
        </section>

        {/* ── CTA BANNER ── */}
        <section className="lnd-section">
          <div className="lnd-cta-banner">
            <div style={{ fontFamily: "'Syne',sans-serif", fontSize: "clamp(28px,4vw,46px)", fontWeight: 800, letterSpacing: "-0.025em", marginBottom: 14 }}>
              Ready to land your dream job?
            </div>
            <p style={{ fontSize: 16, color: "var(--lnd-tx2)", marginBottom: 32, maxWidth: 480, margin: "0 auto 32px" }}>
              Join thousands of job seekers using AI to cut their job search time in half. Free to start.
            </p>
            <button className="lnd-cta-big" style={{ fontSize: 16, padding: "16px 36px" }} onClick={() => window.location.href = "/signup"}>
              Start for free — no card needed →
            </button>
          </div>
        </section>

        {/* ── FOOTER ── */}
        <footer className="lnd-footer">
          <div className="lnd-logo" style={{ fontSize: 14 }}>
            <div className="lnd-logo-icon" style={{ width: 28, height: 28, fontSize: 14, borderRadius: 8 }}>🤖</div>
            AI Job Copilot
          </div>
          <div style={{ fontSize: 12, color: "var(--lnd-tx3)" }}>© 2025 AI Job Copilot. Career Productivity SaaS.</div>
          <div className="lnd-footer-links">
            <a href="/pricing">Pricing</a>
            <a href="/privacy">Privacy</a>
            <a href="/terms">Terms</a>
            <a href="/refund">Refund</a>
            <a href="/login">Login</a>
          </div>
        </footer>

      </div>
    </>
  );
}
